# Generated by Django 2.1.2 on 2018-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_organico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
